org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.17.2
loom_version=1.10.5
fabric_api_version=0.116.10+1.21.1
fabric_kotlin_version=1.13.10+kotlin.2.3.20
cobblemon_version=YgmyyFcs

mod_version=2.1.1-cobblemon1.8
maven_group=com.cobbleclub
archives_base_name=cobbleclub-crates
